# Generated by Django 5.0.6 on 2024-07-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="patient",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
