# Generated by Django 5.0.6 on 2024-07-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0002_remove_patient_phone_number_patient_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
