# Generated by Django 5.0.6 on 2024-07-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0004_patient_created_at_patient_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
