# Generated by Django 5.0.6 on 2024-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0005_alter_treatment_remaining_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Payment Receieved Date"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="remaining_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=models.DecimalField(decimal_places=2, max_digits=10),
                max_digits=10,
            ),
        ),
    ]
