# Generated by Django 5.0.6 on 2024-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0006_alter_treatment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
