# Generated by Django 5.0.6 on 2024-08-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dental", "0007_alter_treatment_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Payment Received Date"
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
